spring.application.name=bookingService

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=create

logging.level.org.springframework.security=DEBUG

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080

jwt.secret=995c1865e8b0dbf557face906fd220fd45288bafecb66baa1397d00fe58f25244051193668b27e2984b88f2e7f1b9300d802df0f3231def3ee2486c61f6cec68
jwt.expiration.ms=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=springtest67@gmail.com
spring.mail.password=ckkanufeaynxxlzr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true